# Generated by Django 3.2.8 on 2021-10-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_race_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='race',
            table='race',
        ),
    ]
