# Generated by Django 3.2.8 on 2021-10-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_race_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='is_active',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='race',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='start_time',
        ),
        migrations.AddField(
            model_name='race',
            name='name',
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
