# Generated by Django 3.2.8 on 2021-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20211022_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.BooleanField(),
        ),
    ]
