# Generated by Django 3.2.8 on 2021-10-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_race_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
